# Generated by Django 4.1.1 on 2022-10-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dane',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
